<?php
namespace Oaza\Application\Adapter\Drivers\DummyDriver\RouteRepository;

use \Oaza\Application\Adapter\Drivers\DummyDriver\DummyDriver;
use \Oaza\Application\Adapter\Entities\RouteEntity;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-20 at 01:29:49.
 */
class RouteEntityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RouteEntity
     */
    protected $object;

    /**
     * @var RouteEntity
     */
    protected $object2;

    /**
     * @var RouteEntity
     */
    protected $object3;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $dummyDriver = new DummyDriver();
        $routeRepository = $dummyDriver->getRouteRepository();

        $this->object = $routeRepository->findRouteEntity(1);
        $this->object2 = $routeRepository->getRouteEntity('/');
        $this->object3 = $routeRepository->findRouteEntity(2);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    public function testGetPageId()
    {
        $this->assertEquals('1',$this->object->getPageId());
        $this->assertEquals('1',$this->object2->getPageId());
        $this->assertEquals('2',$this->object3->getPageId());
    }

    public function testGetPath()
    {
        $this->assertEquals('/',$this->object->getPath());
        $this->assertEquals('/',$this->object2->getPath());
        $this->assertEquals('/new-page',$this->object3->getPath());
    }

    public function testGetPresenter()
    {
        $this->assertEquals('Homepage',$this->object->getPresenter());
        $this->assertEquals('Homepage',$this->object->getPresenter());
        $this->assertEquals('Homepage',$this->object->getPresenter());
    }

}
