<?php
namespace Oaza\Translator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-20 at 01:51:54.
 */
class DatabaseTranslatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DatabaseTranslator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $driver = new \Oaza\Application\Adapter\Drivers\DummyDriver\DummyDriver();
        $this->object = new DatabaseTranslator($driver->getTranslateRepository()->prepareTranslateEntitiesForCurrentPage());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Oaza\Translator\DatabaseTranslator::translate
     */
    public function testTranslate()
    {
        $this->object->setLanguage('sk');
        $this->assertEquals('Potvrdiť', $this->object->translate('MESSAGE_BUTTON_SUBMIT'));
        $this->assertEquals('Zrušiť', $this->object->translate('MESSAGE_BUTTON_CANCEL'));

        $this->assertEquals('Test', $this->object->translate('MESSAGE_BUTTON_TEST'));
        $this->assertEquals('Test', $this->object->translate('MESSAGE_BUTTON_TEST',1));
        $this->assertEquals('Testov', $this->object->translate('MESSAGE_BUTTON_TEST',5));
        $this->assertEquals('Testov', $this->object->translate('MESSAGE_BUTTON_TEST',-5));
        $this->assertEquals('Testy', $this->object->translate('MESSAGE_BUTTON_TEST',-3));
        $this->assertEquals('Testy', $this->object->translate('MESSAGE_BUTTON_TEST',3));

    }
}
