<?php
namespace Oaza\Translator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-16 at 23:22:58.
 */
class DummyTranslatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DummyTranslator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DummyTranslator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Oaza\Translator\DummyTranslator::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
