<?php
namespace Oaza;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-18 at 10:15:18.
 */
class OazaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Oaza
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Oaza( new \Oaza\Application\Adapter\Drivers\DummyDriver\DummyDriver() );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Oaza\Oaza::addJavascriptLibrary
     * @todo   Implement testAddJavascriptLibrary().
     */
    public function testAddJavascriptLibrary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Oaza\Oaza::getDatabaseAdapter
     * @todo   Implement testGetDatabaseAdapter().
     */
    public function testGetDatabaseAdapter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Oaza\Oaza::registerExternalSources
     * @todo   Implement testRegisterExternalSources().
     */
    public function testRegisterExternalSources()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Oaza\Oaza::buildExternalSources
     * @todo   Implement testBuildExternalSources().
     */
    public function testBuildExternalSources()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Oaza\Oaza::install
     * @todo   Implement testInstall().
     */
    public function testInstall()
    {
        $this->object->install();
    }

    /**
     * @covers Oaza\Oaza::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        $this->object->update();
    }
}
