<?php

namespace Oaza\Application\Adapter\Drivers\DummyDriver;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-16 at 23:47:02.
 */
class DummyDriverTest extends \PHPUnit_Framework_TestCase {

    /**
     *
     * @var Name of the class 
     */
    protected $className;
    
    /**
     * @var DummyDriver
     */
    protected $firstDriver;

    /**
     *
     * @var DummyDriver
     */
    protected $secondDriver;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->className = 'Oaza\Application\Adapter\Drivers\DummyDriver\DummyDriver';
        $this->firstDriver = new DummyDriver;
        $this->secondDriver = new DummyDriver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Oaza\Application\Adapter\Drivers\DummyDriver::getControlRepository
     * @todo   Implement testGetControlRepository().
     */
    public function testGetControlRepository() {
        $this->assertNotNull($this->firstDriver->getControlRepository());
        $this->assertNotNull($this->secondDriver->getControlRepository());    
        
        $this->assertInstanceOf($this->className, $this->firstDriver);
        $this->assertInstanceOf($this->className, $this->secondDriver);
        
        $firstSameRepository = $this->firstDriver->getControlRepository();
        $secondSameRepository = $this->firstDriver->getControlRepository();
        $this->assertSame($firstSameRepository, $secondSameRepository);

        $firstNotSameRepository = $this->firstDriver->getControlRepository();
        $secondNotSameRepository = $this->secondDriver->getControlRepository();
        $this->assertNotSame($firstNotSameRepository, $secondNotSameRepository);
    }

}
